# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, lambda, x64, linux]
    environment: dev

    steps:
      - run: ls
